/* config.h — generated by CMake */

#ifndef __config_h__
#define __config_h__

#define PACKAGE_NAME "${PROJECT_NAME}"
#define PACKAGE_VERSION "${PROJECT_VERSION}"
#define PACKAGE_STRING "${PROJECT_NAME} ${PROJECT_VERSION}"

#cmakedefine01 USE_BLAS

#endif
